name: fungine
version: "0.1.0.0"
category: Games
author: Jonathan Durr
maintainer: jmdurr@gmail.com
copyright: 2020 Jonathan Durr
license: BSD3
github: jmdurr/fungine

extra-source-files:
  - README.md

default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude
  - TupleSections

data-dir: resources

dependencies:
  - protolude >=0.2 && <0.3
  - chronos >= 1.0 && < 1.1
  - bytestring >= 0.10 && < 0.11
  - JuicyPixels >= 3.3 && < 3.4
  - JuicyPixels-extra >= 0.4 && < 0.5
  - OpenGL >= 3.0 && < 3.1
  - vector >= 0.12 && < 0.13
  - directory >= 1.3 && < 1.4
  - filepath >= 1.4 &&  < 1.5

library:
  source-dirs: src

  default-extensions:
    - TupleSections

  ghc-options: -Wall

  dependencies:
    - base >=4.7 && <5
    - GLFW-b >=3.2 && <3.3
    - stm >=2.5 && <2.6
    - containers >=0.6 && <0.7
    - text >=1.2 && <1.3
    - chronos >=1.0 && < 1.1
    - hmatrix >= 0.20 && < 0.21

executables:
  fungine-exe:
    main: Main.hs

    source-dirs: app

    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

    dependencies:
      - base
      - fungine

tests:
  fungine-test:
    main: Spec.hs

    source-dirs: test

    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

    dependencies:
      - base
      - fungine
      - hspec >=2.7 && <2.8
